### ISSUE TITLE
Use Other inputs

### ISSUE THREAD

**Issue by ilsenatorov** [CATH-summer-2017/domchop-pymol#5]
add an option of using other input strings

**Comment by shouldsee** [comment]
I think this issue is a good point to start documenting the INPUT OUPUT format that could be recognised by the script.


Feel free to edit this, but preferably we should document it in an .md file to allow for trackable collaboration.
## INPUT:
### Chopping:
| alias | example | status|
|:----- |:-------|:------ |
| THE string|  "10gs D2-78[A]+187-208[A] D79-186[A] F209-209[A]"| |  implemented |
| domall  | "1.2.78.187.208:2.79.186"  |  not implemented (i guess>)|


---------
## OUPUT:
| alias | example | status|
|:----- |:-------|:------ |
| Chopping-rendered Script | [blah](blah) |  implemented |
| Superposition-rendered Script  | [blah](blah) |  in process |

**Comment by ilsenatorov** [comment]
not necessary
